version: '2'
plugins:
  editorconfig:
    enabled: true
  tslint:
    enabled: false
  eslint:
    enabled: true
    channel: 'eslint-6'
    config:
      config: .eslintrc-cc.json
  fixme:
    enabled: true
  git-legal:
    enabled: true
exclude_patterns:
  - '**/temp/'
  - '**/node_modules/'
