version: '2'
plugins:
  duplication:
    enabled: true
  editorconfig:
    enabled: true
  eslint:
    enabled: true
    config:
      config: .eslintrc-cc.json
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
    config: .markdownlint.yaml
  nodesecurity:
    enabled: true
  sass-lint:
    enabled: true
  scss-lint:
    enabled: true
  structure:
    enabled: true
exclude_patterns:
  - '**/.github'
  - '**/.husky'
  - '**/.vscode'
  - '**/dist'
  - '**/temp'
  - '**/test'
  - '**/docs'
  - '**/docs-tmp'
  - '**/etc'
  - '**/node_modules/'
  - '**/*.svg'
  - '**/*.md'
  - '**.*.spec.ts'
  - '**/commitlint.config.js'
