---
engines:
  duplication:
    enabled: true
  metric:
    enabled: true
  remark-int:
    enabled: true
  coverage:
    enabled: true
  eslint:
    enabled: true
exclude_paths:
  - '.circleci/**'
  - '.github/**'
  - '.vscode/**'
  - '**.json'
  - '**.yml'
  - '**.md'
  - 'commitlint.config.js'
