version: '2'
plugins:
  editorconfig:
    enabled: true
  tslint:
    enabled: false
  eslint:
    enabled: true
    channel: 'eslint-7'
    config:
      config: .eslintrc.json
  fixme:
    enabled: true
  git-legal:
    enabled: true
exclude_patterns:
  - '**/.github'
  - '**/.circleci'
  - '**/.vscode'
  - '**/dist'
  - '**/temp'
  - '**/test'
  - '**/docs'
  - '**/node_modules/'
