name: Development CI

on:
  push:
    branches:
      - development

env:
  CI: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x, 13.x, 14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: nodejs project information
        id: projectinfo
        uses: gregoranders/nodejs-project-info@v0.0.6
      - name: npm install
        run: |
          npm install
      - name: npm run build
        run: |
          npm run build
      - name: npm test
        run: |
          npm test
      - name: code coverage
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '14.x'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./temp/coverage/lcov.info
      - name: publish code coverage to code climate
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '14.x'
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm test
          coverageLocations: |
            ./temp/coverage/lcov.info:lcov
