name: Master CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
      env:
        CI: true
    - name: npm run build
      run: |
        npm run build
      env:
        CI: true
    - name: npm test
      run: |
        npm test
      env:
        CI: true
    - name: code coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/lcov.info
      env:
        CI: true
    - name: publish code coverage to code climate
      if: matrix.os == 'ubuntu-latest'
      uses: paambaati/codeclimate-action@v2.3.0
      env:
        CI: true
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE }}
      with:
        coverageCommand: npm run test
        debug: true
